# 공통 영역
spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
# profile 설정 영역
---
spring:
  profiles: local
  datasource:
    data: classpath:data-h2.sql #시작할 때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true